spring:
  application:
    name: trailplanner

  datasource:
    url: jdbc:postgresql://localhost:5432/trailplanner
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true